%YAML:1.0
image_width: 600
image_height: 600
camera_matrix: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 156.170115, 0., 300, 0.,
       156.170115, 300, 0., 0., 1. ]
distortion_coefficients: !!opencv-matrix
   rows: 4
   cols: 1
   dt: d
   data: [ 0., 0., 0., 0.]
